- name: install and run nginx
  hosts: web
  become: yes #equl to -b in adhoc commands,getting root aceess
  tasks: #list of modules/collections/tasks
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
