- name: checking condition of whether the user is existed or not
  hosts: localhost
  become: yes
  tasks:
  - name: checking user is added or not
    ansible.builtin.command: id expense
    ignore_errors: yes
    

  - name: printing hello if is true
    ansible.builtin.debug:
      msg: "Hello frnd"