- name: default filter
  hosts: localhost
  tasks:
    - name: printing default
      ansible.builtin.debug:
        msg: " welcome to {{city | default('hyderabad') }}"
    
- name: upper case filter
  hosts: localhost
  vars:
    greeting: "Hello, Good Afternoon"
  tasks:
    - name: converitng to upper case
      ansible.builtin.debug:
        msg: "{{greeting | upper}}"

- name: lower case filter
  hosts: localhost
  vars:
    greeting: "Hello, Good Afternoon"
  tasks:
    - name: converitng to lower case
      ansible.builtin.debug:
        msg: "{{greeting | lower}}"

- name: removing duplicate filter
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 1, 3, 5]
  tasks:
    - name: remove duplicate
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"