- name: default filter
  hosts: localhost
  tasks:
    - name: printing default
      ansible.builtin.debug:
        msg: " welcome to {{city | default('hyderabad') }}"
    
- name: upper case filter
  hosts: localhost
  vars:
    greeting: "Hello, Good Afternoon"
  tasks:
    - name: converitng to upper case
      ansible.builtin.debug:
        msg: "{{greeting | upper}}"

- name: lower case filter
  hosts: localhost
  vars:
    greeting: "Hello, Good Afternoon"
  tasks:
    - name: converitng to lower case
      ansible.builtin.debug:
        msg: "{{greeting | lower}}"

- name: removing duplicate filter
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 1, 3, 5]
  tasks:
    - name: remove duplicate
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: min and max filter
  hosts: localhost
  vars:
    age: [18, 25, 30, 70 ]
  tasks:
    - name: min and max number
      ansible.builtin.debug:
        msg: "minimum age is {{ age | min}}, maximum age is {{age | max}}"

- name: converting dictionary into items
  hosts: localhost
  vars:
    my_dict:  #this is a dictionary,map or key/pair values
    Course: "Devops with AWS"
    Student: "Guru"
    Duration: "120hrs"
  tasks: 
    - name: before conversion
      ansible.builtin.debug:
       msg: "before conversion: {{my_dict}}"

    - name: after conversion
      ansible.builtin.debug:
        msg: "after conversion: {{ my_dict | dict2items }}"

    