- name: installing packages
  hosts: web
  become: yes
  tasks:
    - name: install package
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
      loop:
      - mysql
      - nginx
      