- name: installing and removing packages
  hosts: web
  tasks: 
    - name: install and remove package
      ansible.builtin.dnf:

    loop:
    - { name: 'mysql', state: 'latest' } # state:latest refers to installing of package
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    

