- name: installing and removing packages
  hosts: web
  become: yes
  tasks: 
    - name: install and remove package
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"

      loop:
      - { name: 'mysql', state: 'latest' } # state:latest refers to installing of package
      - { name: 'nginx', state: 'absent' } # state:absent refers to removing of package
      - { name: 'postfix', state: 'absent' }
    

