- name: command vs shell module
  hosts: localhost
  tasks:
    - name: command module
      ansible.builtin.command: "echo 'hi this is command module' > /temp/command.txt"
    - name: shell module
      ansible.builtin.shell: "echo 'hi this is shell module' > /temp/shell.txt"